PrivateMessenger/PrivateMessenger/Models/CustomUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.Models
{
    public class CustomUser : IdentityUser
    {
        [MaxLength(30)]
        public string Name { get; set; }
        [MaxLength(30)]
        public string Surname { get; set; }
        public byte Age { get; set; }
    }
}

PrivateMessenger/PrivateMessenger/Models/ErrorViewModel.cs
using System;

namespace PrivateMessenger.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrivateMessenger/PrivateMessenger/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.Models
{
    public class Message
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(2000)]
        public string Text { get; set; }
        [ForeignKey("Sender")]
        public string SenderId { get; set; }
        public CustomUser Sender { get; set; }
        [ForeignKey("Reciever")]
        public string RecieverId { get; set; }
        public CustomUser Reciever { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

PrivateMessenger/PrivateMessenger/ViewModels/VmMessage.cs
using PrivateMessenger.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.ViewModels
{
    public class VmMessage
    {
        public List<Message> Messages { get; set; }
        public CustomUser User { get; set; }
        public string SenderId { get; set; }
    }
}

PrivateMessenger/PrivateMessenger/ViewModels/VmRegister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.ViewModels
{
    public class VmRegister
    {
        [MaxLength(30)]
        public string Name { get; set; }
        [MaxLength(30)]
        public string Surname { get; set; }
        [MaxLength(50), Required]
        public string Email { get; set; }
        [MaxLength(30), Required]
        public string Password { get; set; }
    }
}

PrivateMessenger/PrivateMessenger/Controllers/AccountController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PrivateMessenger.Data;
using PrivateMessenger.Models;
using PrivateMessenger.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.Controllers
{
    public class AccountController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public AccountController(AppDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(VmRegister model)
        {
            if (ModelState.IsValid)
            {
                CustomUser user = new CustomUser()
                {
                    Name = model.Name,
                    Surname = model.Surname,
                    UserName = model.Email,
                    Email = model.Email
                };

                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("index", "home");
                }
                else
                {
                    ModelState.AddModelError("", "Not registered");
                }
            }

            return View(model);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VmRegister model)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Not registered");
                }
            }

            return View(model);
        }

        public IActionResult Logout()
        {
            _signInManager.SignOutAsync();
            return RedirectToAction("Index", "home");
        }
    }
}

PrivateMessenger/PrivateMessenger/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PrivateMessenger.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Chat()
        {
            return View();
        }

    }
}

PrivateMessenger/PrivateMessenger/Controllers/MessengerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PrivateMessenger.Data;
using PrivateMessenger.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrivateMessenger.Controllers
{
    public class MessengerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public MessengerController(AppDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Index()
        {
            string callerId = _userManager.GetUserId(User);
            return View(_context.CustomUsers.Where(cu => cu.Id != callerId).ToList());
        }

        public IActionResult Chat(string recieverId)
        {
            string senderId = _userManager.GetUserId(User);
            VmMessage model = new VmMessage();
            model.User = _context.CustomUsers.Find(recieverId);
            model.Messages = _context.Messages.Where(m => (m.SenderId == senderId && m.RecieverId == recieverId) || (m.SenderId == recieverId && m.RecieverId == senderId)).ToList();
            model.SenderId = senderId;

            return View(model);
        }
    }
}

PrivateMessenger/PrivateMessenger/Views/Home/Chat.cshtml
@{
    ViewData["Title"] = "Chat";
}

<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-2">User</div>
        <div class="col-4"><input type="text" id="userInput" /></div>
    </div>
    <div class="row">
        <div class="col-2">Message</div>
        <div class="col-4"><input type="text" id="messageInput" /></div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-6">
        <ul id="messagesList"></ul>
    </div>
</div>

PrivateMessenger/PrivateMessenger/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrivateMessenger/PrivateMessenger/Views/Messenger/Chat.cshtml
@model VmMessage
@{
    ViewData["Title"] = "Chat";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mb-5">Send message to @Model.User.Name</h1>
        </div>
        <hr />
        <div class="col-lg-12">
            <div class="messageContainer mb-3">
                @foreach (var item in Model.Messages)
                {
                    <p class="@(item.SenderId==Model.SenderId?"sender":"reciever")">@item.Text</p>
                }
                @*<p class="sender">Salam</p>*@
                @*<p class="reciever">Alekum salam</p>*@
                @*<p class="typing">Typing...</p>*@
            </div>
        </div>

        <div class="col-lg-12">
            <div class="input-group mb-3">
                <input type="text" class="form-control" id="messengerInput" placeholder="Type message...">
                <input hidden id="recieverId" value="@Model.User.Id">
                <button class="btn btn-outline-secondary" type="button" id="messengerButton">Send</button>
            </div>
        </div>
    </div>
</div>

PrivateMessenger/PrivateMessenger/Views/Messenger/Index.cshtml
@model List<CustomUser>
@{
    ViewData["Title"] = "Index";
}


<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h1>Friends list</h1>
            <ul>
                @foreach (var item in Model)
                {
                    <li><a asp-controller="Messenger" asp-action="Chat" asp-route-recieverId="@item.Id">@item.Email</a></li>
                }
            </ul>
        </div>
    </div>
</div>

PrivateMessenger/PrivateMessenger/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor _httpContext
@inject UserManager<IdentityUser> _userManager
@inject SignInManager<IdentityUser> _signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrivateMessenger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrivateMessenger</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark">@_userManager.GetUserName(User)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#">/</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Messenger" asp-action="Index">Friends</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#">/</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#">/</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PrivateMessenger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>